# Generated by Django 4.1.7 on 2023-03-17 14:35

import backend.utils.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('rss', models.URLField(max_length=1000, verbose_name='rss')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.URLField(max_length=1000, null=True, verbose_name='link')),
                ('image', models.URLField(max_length=1000, verbose_name='image')),
                ('language', models.CharField(max_length=5, verbose_name='language')),
                ('copyright', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('subtitle', models.CharField(max_length=4000, null=True, verbose_name='subtitle')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('summary', models.CharField(max_length=4000, verbose_name='summary')),
                ('owner', models.EmailField(blank=True, max_length=254, verbose_name='owner')),
                ('categories', models.CharField(max_length=255, verbose_name='categories')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'episodic'), (2, 'serial')], default=1, verbose_name='type')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique='True', verbose_name='slug')),
                ('description', models.TextField(max_length=4000, verbose_name='description')),
                ('explicit', models.PositiveSmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'clean')], default=1, verbose_name='explicit')),
            ],
        ),
        migrations.CreateModel(
            name='AudioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=10000, null=True, verbose_name='subtitle')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='author')),
                ('link', models.URLField(max_length=1000, null=True, verbose_name='link')),
                ('summary', models.CharField(max_length=10000, null=True, verbose_name='summary')),
                ('description', models.TextField(max_length=4000, null=True, verbose_name='description')),
                ('image', models.URLField(max_length=1000, null=True, verbose_name='image')),
                ('guid', models.CharField(max_length=255, verbose_name='guid')),
                ('pub_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published')),
                ('language', models.CharField(max_length=20, null=True, verbose_name='language')),
                ('explicit', models.PositiveSmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'clean')], default=1, null=True, verbose_name='explicit')),
                ('season', models.PositiveSmallIntegerField(null=True, verbose_name='season')),
                ('episode_num', models.PositiveSmallIntegerField(null=True, verbose_name='episode number')),
                ('episode_type', models.PositiveSmallIntegerField(choices=[(1, 'full'), (2, 'trailer'), (3, 'bonus')], default=1, null=True, verbose_name='episode type')),
                ('duration', models.CharField(max_length=255, null=True, verbose_name='duration')),
                ('audio_link', models.URLField(max_length=1000, null=True, verbose_name='audio_link')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audiochannel')),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('segmentor', models.JSONField(verbose_name='word to utterance model')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('speaker', models.CharField(max_length=255, null=True, verbose_name='speaker')),
                ('start', models.CharField(max_length=20, verbose_name='start time')),
                ('end', models.CharField(max_length=20, verbose_name='end time')),
                ('text', models.CharField(max_length=4000, verbose_name='text')),
                ('text_coref', models.CharField(max_length=4000, null=True, verbose_name='text')),
                ('summary', models.CharField(max_length=255, null=True, verbose_name='text')),
                ('segmentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.segmentation')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('json', models.JSONField(verbose_name='json')),
                ('text', models.TextField(verbose_name='text')),
                ('speech2txt', models.JSONField(verbose_name='speech to text model')),
                ('runtime', models.DurationField(verbose_name='runtime')),
                ('created', models.DateTimeField(verbose_name='created time')),
                ('language', models.CharField(max_length=255, verbose_name='language')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audioitem')),
            ],
        ),
        migrations.AddField(
            model_name='segmentation',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transcription'),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('query', models.CharField(max_length=255, verbose_name='query')),
                ('platform', models.CharField(max_length=255, verbose_name='platform')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utterance')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('document', models.CharField(max_length=255, verbose_name='document')),
                ('supports', models.BooleanField(verbose_name='supports')),
                ('comment', models.CharField(max_length=255, verbose_name='comment')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.query')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', backend.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utterance')),
            ],
        ),
    ]
