# Generated by Django 4.1.7 on 2023-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="label",
            field=models.TextField(verbose_name="label"),
        ),
    ]
