# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="qualifier",
            field=models.CharField(
                default="", max_length=255, verbose_name="qualifier"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classification",
            name="source",
            field=models.CharField(default="", max_length=255, verbose_name="source"),
            preserve_default=False,
        ),
    ]
