# Generated by Django 4.1.7 on 2023-03-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_classification_qualifier_classification_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classification",
            name="source",
        ),
        migrations.AddField(
            model_name="classification",
            name="agent",
            field=models.CharField(
                default="test_user", max_length=100, verbose_name="agent"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="agent",
            field=models.CharField(
                default="test_user", max_length=100, verbose_name="agent"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="query",
            name="agent",
            field=models.CharField(
                default="test_user", max_length=100, verbose_name="agent"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="comment",
            field=models.CharField(max_length=500, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.CharField(max_length=500, verbose_name="document"),
        ),
        migrations.AlterField(
            model_name="document",
            name="supports",
            field=models.CharField(max_length=10, verbose_name="document"),
        ),
        migrations.AlterField(
            model_name="query",
            name="platform",
            field=models.CharField(max_length=100, verbose_name="platform"),
        ),
        migrations.AlterField(
            model_name="query",
            name="query",
            field=models.CharField(max_length=500, verbose_name="query"),
        ),
    ]
