# Generated by Django 4.1.7 on 2023-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_classification_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="label",
            field=models.TextField(null=True, verbose_name="label"),
        ),
    ]
