# Generated by Django 4.1.7 on 2023-03-25 07:57

import backend.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_classification_source_classification_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiochannel",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="audioitem",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="supports",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Refutes"), (2, "Not Relevant"), (3, "Supports")],
                verbose_name="supports",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="segmentation",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="utterance",
            name="uuid",
            field=backend.utils.fields.UUIDField(
                blank=True,
                editable=False,
                max_length=36,
                unique=True,
                verbose_name="uuid",
            ),
        ),
    ]
