# Generated by Django 4.1.7 on 2023-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_classification_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="utterance",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="hidden"),
        ),
    ]
