# Generated by Django 4.1.7 on 2023-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_utterance_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioitem",
            name="rss_index",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="rss index"
            ),
            preserve_default=False,
        ),
    ]
