# Generated by Django 4.1.7 on 2023-03-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_audiochannel_uuid_alter_audioitem_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="comment",
            field=models.CharField(
                max_length=500, null=True, verbose_name="comment"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="supports",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Refutes"), (2, "Not Relevant"), (3, "Supports")],
                null=True,
                verbose_name="supports",
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="platform",
            field=models.CharField(
                max_length=100, null=True, verbose_name="platform"
            ),
        ),
    ]
