# Generated by Django 4.1.7 on 2023-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_document_comment_alter_document_supports_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="category",
            field=models.CharField(
                default="Checkworthy", max_length=255, verbose_name="category"
            ),
            preserve_default=False,
        ),
    ]
