# Generated by Django 4.1.7 on 2023-04-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audioitem_rss_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utterance',
            old_name='summary',
            new_name='microfacts',
        ),
    ]
