# Generated by Django 4.1.7 on 2023-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_summary_utterance_microfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='claimspan',
            field=models.JSONField(null=True, verbose_name='summarized text info'),
        ),
    ]
