# Generated by Django 4.1.7 on 2023-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_utterance_claimspan"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="prolific_session",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Prolific session id"
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="prolific_study",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Prolific study id"
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="prolific_session",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Prolific session id"
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="prolific_study",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Prolific study id"
            ),
        ),
        migrations.AlterField(
            model_name="utterance",
            name="claimspan",
            field=models.JSONField(
                null=True, verbose_name="text span containing claim"
            ),
        ),
    ]
