# Generated by Django 4.1.7 on 2023-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_classification_toloka_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="valid",
            field=models.BooleanField(default=False, verbose_name="valid"),
        ),
        migrations.AddField(
            model_name="query",
            name="valid",
            field=models.BooleanField(default=False, verbose_name="valid"),
        ),
    ]
