# Generated by Django 4.1.7 on 2023-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_document_valid_query_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="comment",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="comment"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.CharField(max_length=1000, verbose_name="document"),
        ),
    ]
