# Generated by Django 4.1.7 on 2023-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_document_comment_alter_document_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="query",
            field=models.CharField(max_length=1000, verbose_name="query"),
        ),
    ]
