# Generated by Django 4.1.7 on 2023-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_query_query"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utterance",
            name="hidden",
        ),
        migrations.AddField(
            model_name="utterance",
            name="visibility",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Hidden"),
                    (1, "Transcription Only"),
                    (2, "Fact Check, Checkworthiness, Claimspan"),
                    (3, "FC, CW, CS, Motivation"),
                    (4, "FC, CW, CS, Motivation, Advertising"),
                    (9, "All Microtasts"),
                ],
                null=True,
                verbose_name="visibility",
            ),
        ),
    ]
