# Generated by Django 4.1.7 on 2023-05-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_utterance_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utterance",
            name="visibility",
            field=models.JSONField(
                null=True,
                verbose_name="list of visible task cards, null for show all",
            ),
        ),
    ]
