# Generated by Django 4.1.7 on 2023-05-08 18:22

import backend.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_utterance_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    backend.utils.fields.UUIDField(
                        blank=True,
                        editable=False,
                        max_length=36,
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "agent",
                    models.CharField(max_length=100, verbose_name="agent"),
                ),
                (
                    "prolific_study",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Prolific study id",
                    ),
                ),
                (
                    "prolific_session",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Prolific session id",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="created time")),
                (
                    "last_updated",
                    models.DateTimeField(verbose_name="last updated time"),
                ),
                (
                    "survey",
                    models.JSONField(
                        null=True, verbose_name="user initial survey answers"
                    ),
                ),
                (
                    "diarization",
                    models.JSONField(
                        null=True, verbose_name="user diarization labels"
                    ),
                ),
            ],
        ),
    ]
