# Generated by Django 4.1.7 on 2023-05-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_agentsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsession",
            name="segmentation",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.segmentation",
            ),
            preserve_default=False,
        ),
    ]
