# Generated by Django 4.1.7 on 2023-05-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_agentsession_segmentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiochannel",
            name="study_category",
            field=models.CharField(
                max_length=255, null=True, verbose_name="study category"
            ),
        ),
    ]
