# Generated by Django 4.1.7 on 2023-05-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_audiochannel_study_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsession",
            name="finished",
            field=models.BooleanField(
                default=False, verbose_name="annotation submitted to toloka"
            ),
        ),
    ]
