# Generated by Django 4.1.7 on 2023-05-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agentsession_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochannel',
            name='summary',
            field=models.TextField(verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='audioitem',
            name='summary',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
    ]
