# Generated by Django 4.1.7 on 2023-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agentsession_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochannel',
            name='categories',
            field=models.CharField(max_length=4000, verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='audioitem',
            name='summary',
            field=models.CharField(max_length=20000, null=True, verbose_name='summary'),
        ),
    ]
