# Generated by Django 4.1.7 on 2023-05-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_audiochannel_summary_alter_audioitem_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiochannel',
            name='summary',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
    ]
