# Generated by Django 4.1.7 on 2023-05-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_audiochannel_categories_and_more'),
        ('api', '0020_alter_audiochannel_summary_alter_audioitem_summary'),
    ]

    operations = [
    ]
