# Generated by Django 4.1.7 on 2023-05-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_merge_20230521_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioitem',
            name='summary',
            field=models.TextField(null=True, verbose_name='summary'),
        ),
    ]
