# Generated by Django 4.1.7 on 2023-06-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_audioitem_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="utterance",
            name="asr_prob_avg",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="ASR Probability Average",
            ),
        ),
        migrations.AddField(
            model_name="utterance",
            name="asr_prob_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                verbose_name="ASR Probability Minimum",
            ),
        ),
    ]
