upstream api {
    server backend:8000;
}

server {
  listen 8080;
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  location / {
    root /var/www/react;    
    try_files $uri /index.html;
  }

  location /api/ {
    proxy_pass http://api;
    proxy_set_header Host $http_host;
  }

  location /media/ {
    alias /var/www/media/;
  }
}